{{- if not .Values.postgresql.install -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-db-init
  namespace: {{ .Release.Namespace }}
spec:
  backoffLimit: 2
  template:
    spec:
      restartPolicy: Never
      initContainers:
        - name: wait-db
          image: jwilder/dockerize
          imagePullPolicy: IfNotPresent
          args:
          - -timeout=120s
          - -wait
          - tcp://{{ include "database_host" .}}:5432
      containers:
        - name: db-init
          image: postgres:13-alpine
          imagePullPolicy: Always
          #command: ['sleep', 'infinity']
          command:
            - sh
            - -c
            - psql "host={{ .Values.postgresql.externalhost }} port=5432 dbname=postgres user=$POSTGRES_USER password=$POSTGRES_PASSWORD" -f /initdb.d/init.sql
          env:
            - name: POSTGRESQL_PORT_NUMBER
              value: "5432"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgresql
                  key: postgresql-password
          volumeMounts:
            - name: custom-init-scripts-secret
              mountPath: /initdb.d
      volumes:
        - name: custom-init-scripts-secret
          secret:
            secretName: {{ .Release.Name }}-postgres-init

{{- end -}}