apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-rabbitmq
  namespace: {{ .Release.Namespace }}
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rabbitmq
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rabbitmq
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.9.3-alpine
        imagePullPolicy: IfNotPresent
        ports:
          - name: amqp
            containerPort: 5672
        volumeMounts:
           - name: configuration
             mountPath: /etc/rabbitmq
        resources:
{{toYaml .Values.rabbitmq.resources | indent 11}}
      volumes:
         - name: configuration
           secret:
             secretName: {{ .Release.Name }}-rabbitmq-conf
             items:
               - key: rabbitmq.conf
                 path: rabbitmq.conf
 