{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-geonode
  namespace: {{ .Release.Namespace }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
  - host: {{ .Values.general.externalDomain }}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:    
            name: {{ .Release.Name }}-geonode
            port:
              name: www
      - pathType: Prefix
        path: /geoserver
        backend:
          service:    
            name: {{ .Release.Name }}-geoserver
            port:
              name: http-geoserver
  tls:
  - hosts:
    - {{ .Values.general.externalDomain }}
    secretName: {{ .Values.ingress.secretName }}
{{- end }}