# Load-balancer for SGW
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-geonode
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app.kubernetes.io/name: geonode
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
  - targetPort: 80
    port: 80
    name: www
  - targetPort: 8000
    port: 8000
    name: geonode
  type: {{ .Values.general.serviceType }}
