apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-rabbitmq
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  rabbitmq-password: {{ .Values.rabbitmq.auth.password | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-rabbitmq-conf
  namespace: {{ .Release.Namespace }}
stringData:
  rabbitmq.conf: |-
    ## Username and password
    default_user = {{ .Values.rabbitmq.auth.username }}
    default_pass = {{ .Values.rabbitmq.auth.password }}
    ## Clustering
    #cluster_formation.peer_discovery_backend  = rabbit_peer_discovery_k8s
    #cluster_formation.k8s.host = kubernetes.default.svc.cluster.local
    #cluster_formation.node_cleanup.interval = 10
    #cluster_formation.node_cleanup.only_log_warning = true
    #cluster_partition_handling = autoheal
    # queue master locator
    # queue_master_locator = min-masters
    # enable guest user
    loopback_users.guest = false
    #default_vhost = default-vhost
    #disk_free_limit.absolute = 50MB
    #load_definitions = /app/load_definition.json