# Load-balancer for SGW
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-geoserver
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app.kubernetes.io/name: geoserver
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
  - targetPort: 8080
    port: 8080
    name: http-geoserver
  type: {{ .Values.general.serviceType }}
