# Sync gateway pod
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-geoserver
  namespace: {{ .Release.Namespace }}
spec:
  # This pod can NOT be scaled, because it persists local files
  replicas: 1
  strategy:
    # Need to kill previous pods before running new ones to avoid double-attaching volumes...
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: geoserver
      app.kubernetes.io/instance: {{ .Release.Name }}

  template:
    metadata:
      annotations:
        # Add a checksum to force the re-creation of the pods on every config update
        checksum/conf: {{ .Values.geonode.extraConf | sha256sum }}
        checksum/conf2: {{ .Values.geonode.extraConf2 | sha256sum }}
        checksum/nginx: {{ include "nginx_conf" . | sha256sum }}
      labels:
        app.kubernetes.io/name: geoserver
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      securityContext:
        fsGroup: {{ .Values.general.gid }}
      # Resolving some hardcoded links...
      initContainers:
      - name: busybox
        image: registry.uninett.no/public/busybox:1.33.1-glibc
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: {{ .Values.uid }}
          runAsGroup: {{ .Values.gid }}
        args:
          - /bin/sh
          - -c
          - -x
          - "mkdir -p /geonode/statics && \
            mkdir -p  /geonode/geoserver-data-dir && \
            mkdir -p  /geonode/backup-restore && \
            mkdir -p  /geonode/data && \
            chmod g+wx /geonode/statics && \
            chmod g+wx /geonode/geoserver-data-dir && \
            chmod g+wx /geonode/backup-restore && \
            chmod g+wx /geonode/data"
        volumeMounts:
        - name: persistence
          mountPath: /geonode
          subPath: geonode
      # Initialize default data
      # The tag NEEDS to match with the geoserver tag
      # See https://hub.docker.com/r/geonode/geoserver
      - name: data-dir-conf
        image: geonode/geoserver_data:{{ .Values.geoserver.image.tag }}
        command:
        - sh
        - -c
        - |
          # Copy defaults from data container
          cp -r /tmp/geonode/downloaded/data /geoserver_data

          # Copy overrides from ConfigMap
          cp /overrides/notifier.xml /geoserver_data/data/notifier/

          # Update custom EPSG codes
          cat /geoserver_data/data/user_projections/epsg.properties > /tmp/epsg.properties
          {{- range .Values.geoserver.customEPSGs }}
          echo '{{ . }}' >> /tmp/epsg.properties
          {{- end }}
          {{- range .Values.geoserver.extraCustomEPSGs }}
          echo '{{ . }}' >> /tmp/epsg.properties
          {{- end }}
          sort -u /tmp/epsg.properties > /geoserver_data/data/user_projections/epsg.properties
        volumeMounts:
        - name: persistence
          mountPath: /geoserver_data/data
          subPath: geonode/geoserver-data-dir
        - name: geoserver-conf
          mountPath: /overrides
      containers:
      - name: geoserver
        image: "{{ .Values.geoserver.image.name }}:{{ .Values.geoserver.image.tag }}"
        ports:
        - containerPort: 8080
        env:
        - name: GEONODE_LB_HOST_IP
          value: {{ .Values.general.externalDomain | quote }}
        - name: GEONODE_LB_PORT
          value: {{ .Values.general.externalPort | quote }}
        - name: GEONODE_HOST_IP
          value: {{ .Release.Name }}-geonode
        - name: PUBLIC_PORT
          value: {{ .Values.general.externalPort | quote }}
        - name: DJANGO_URL
          value: http://{{ .Release.Name }}-geonode/
        - name: ENABLE_JSONP
          value: 'true'
        - name: outFormat
          value: text/javascript
        - name: GEOSERVER_JAVA_OPTS
          value: -Djava.awt.headless=true -Xms2G -Xmx4G -XX:PerfDataSamplingInterval=500 -XX:SoftRefLRUPolicyMSPerMB=36000 -XX:-UseGCOverheadLimit -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:ParallelGCThreads=4 -Dfile.encoding=UTF8 -Djavax.servlet.request.encoding=UTF-8 -Djavax.servlet.response.encoding=UTF-8 -Duser.timezone=GMT -Dorg.geotools.shapefile.datetime=false -DGEOSERVER_CSRF_DISABLED=true -DPRINT_BASE_URL=http://localhost:8080/geoserver/pdf
        - name: NGINX_BASE_URL
          value: "{{ include "public_url" . }}/"
        volumeMounts:
        - name: persistence
          mountPath: /geoserver_data/data
          subPath: geonode/geoserver-data-dir
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 5
          failureThreshold: 15
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 180
          periodSeconds: 5
          failureThreshold: 15
        resources:
          requests:
            memory: 2Gi
            cpu: 100m
          limits:
            memory: 4Gi
            cpu: 400m
      volumes:
      - name: geoserver-conf
        configMap:
          name: {{ .Release.Name }}-geoserver-conf
      - name: persistence
        persistentVolumeClaim:
          claimName: {{ .Values.persistentStorage.existingClaimName }}