# Source: geonode/charts/postgresql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: seabee-postgresql
  labels:
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-10.1.4
    app.kubernetes.io/instance: seabee
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  postgresql-postgres-password: "b3JrNE5vd1g0ZQ=="
  postgresql-password: "YWRtaW5uZnNka2xuZmdrbHNk"