# Source: geonode/charts/postgresql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgresql
  labels:
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-10.1.4
    app.kubernetes.io/instance: seabee
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  postgresql-postgres-password: {{ .Values.postgresql.password | b64enc | quote}}
  postgresql-password: {{ .Values.postgresql.postgresqlPassword | b64enc | quote}}