apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-rabbitmq
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: ClusterIP
  ports:
    - name: amqp
      port: 5672
      targetPort: amqp
  selector: 
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/instance: {{ .Release.Name }}
